# Generated by Django 5.2.4 on 2025-07-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Outra', 'Outra')], max_length=50, verbose_name='Marca')),
                ('cor', models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Prata', 'Prata'), ('Cinza', 'Cinza'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Laranja', 'Laranja'), ('Marrom', 'Marrom'), ('Bege', 'Bege'), ('Dourado', 'Dourado'), ('Outra', 'Outra')], max_length=20, verbose_name='Cor')),
                ('tipo', models.CharField(choices=[('Hatch', 'Hatch'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Picape', 'Picape'), ('Esportivo', 'Esportivo')], max_length=20, verbose_name='Tipo')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('motor', models.CharField(max_length=30, verbose_name='Motor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('km', models.IntegerField(verbose_name='Quilometragem')),
                ('cambio', models.CharField(choices=[('Manual', 'Manual'), ('Automático', 'Automático'), ('Automático Sequencial', 'Automático Sequencial'), ('CVT', 'CVT')], max_length=50, verbose_name='Câmbio')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Álcool', 'Álcool'), ('Flex', 'Flex'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], max_length=50, verbose_name='Combustível')),
                ('ipva_pago', models.BooleanField(verbose_name='IPVA pago')),
                ('consumo_cidade', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Consumo na cidade (km/l)')),
                ('consumo_estrada', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Consumo na estrada (km/l)')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='ImagemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_url', models.CharField(max_length=255, verbose_name='URL da foto')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app.carro', verbose_name='Carro')),
            ],
            options={
                'verbose_name': 'Imagem de Carro',
                'verbose_name_plural': 'Imagens de Carros',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da venda')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da venda')),
                ('forma_pagamento', models.CharField(choices=[('À vista', 'À vista'), ('Financiamento', 'Financiamento'), ('Consórcio', 'Consórcio'), ('Cartão de crédito', 'Cartão de crédito')], max_length=50, verbose_name='Forma de pagamento')),
                ('parcelas', models.IntegerField(blank=True, null=True, verbose_name='Parcelas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.carro', verbose_name='Carro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario', verbose_name='Usuário')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoTestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(verbose_name='Data do agendamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('remarcado', 'Remarcado')], default='agendado', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carro', verbose_name='Carro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Agendamento de Test Drive',
                'verbose_name_plural': 'Agendamentos de Test Drive',
            },
        ),
    ]
