# Generated by Django 5.2.5 on 2025-10-24 23:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Outra', 'Outra')], max_length=50, verbose_name='Marca')),
                ('cor', models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Prata', 'Prata'), ('Cinza', 'Cinza'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Laranja', 'Laranja'), ('Marrom', 'Marrom'), ('Bege', 'Bege'), ('Dourado', 'Dourado'), ('Outra', 'Outra')], max_length=20, verbose_name='Cor')),
                ('tipo', models.CharField(choices=[('Hatch', 'Hatch'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Picape', 'Picape'), ('Esportivo', 'Esportivo')], max_length=20, verbose_name='Tipo')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('motor', models.CharField(max_length=30, verbose_name='Motor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('km', models.IntegerField(verbose_name='Quilometragem')),
                ('cambio', models.CharField(choices=[('Manual', 'Manual'), ('Automático', 'Automático'), ('Automático Sequencial', 'Automático Sequencial'), ('CVT', 'CVT')], max_length=50, verbose_name='Câmbio')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Álcool', 'Álcool'), ('Flex', 'Flex'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], max_length=50, verbose_name='Combustível')),
                ('ipva_pago', models.BooleanField(verbose_name='IPVA pago')),
                ('consumo_cidade', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Consumo na cidade (km/l)')),
                ('consumo_estrada', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Consumo na estrada (km/l)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Carro ativo')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracaoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=50, verbose_name='Campo Alterado')),
                ('valor_antigo', models.TextField(blank=True, null=True, verbose_name='Valor Antigo')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Usuário')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='app.carro', verbose_name='Carro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que alterou')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração de Carro',
                'verbose_name_plural': 'Históricos de Alterações de Carros',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_url', models.CharField(max_length=255, verbose_name='URL da foto')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app.carro', verbose_name='Carro')),
            ],
            options={
                'verbose_name': 'Imagem de Carro',
                'verbose_name_plural': 'Imagens de Carros',
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Número de telefone inválido')], verbose_name='Telefone')),
                ('ocupacao', models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário'), ('gerente', 'Gerente')], default='cliente', max_length=20, verbose_name='Ocupação')),
                ('kgs_borracha_doados', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kgs de borracha doados')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Funcionario ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da venda')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da venda')),
                ('forma_pagamento', models.CharField(choices=[('À vista', 'À vista'), ('Financiamento', 'Financiamento'), ('Consórcio', 'Consórcio'), ('Cartão de crédito', 'Cartão de crédito')], max_length=50, verbose_name='Forma de pagamento')),
                ('parcelas', models.IntegerField(blank=True, null=True, verbose_name='Parcelas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.carro', verbose_name='Carro')),
                ('cliente', models.ForeignKey(blank=True, limit_choices_to={'ocupacao': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='app.usuario', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(limit_choices_to={'ocupacao': 'funcionario'}, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to='app.usuario', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
