# Generated by Django 5.2.7 on 2025-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Carro ativo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='kgs_borracha_doados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kgs de borracha doados'),
        ),
    ]
