# Generated by Django 5.2.5 on 2025-11-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='pcd',
            field=models.BooleanField(default=False, verbose_name='Adaptado para PCD'),
        ),
    ]
