# Generated by Django 5.2.3 on 2025-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="motor",
            field=models.CharField(max_length=30, verbose_name="Motor"),
        ),
    ]
