# Generated by Django 5.2.4 on 2025-07-24 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testdrive_delete_agendamentotestdrive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdrive',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='testdrive',
            name='usuario',
        ),
    ]
