# Generated by Django 5.2.3 on 2025-06-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_carro_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da venda'),
        ),
    ]
