# Generated by Django 5.2.3 on 2025-06-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_venda_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Prata', 'Prata'), ('Cinza', 'Cinza'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Laranja', 'Laranja'), ('Marrom', 'Marrom'), ('Bege', 'Bege'), ('Dourado', 'Dourado'), ('Outra', 'Outra')], max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Outra', 'Outra')], max_length=50, verbose_name='Marca'),
        ),
    ]
