# Generated by Django 5.2.5 on 2025-08-31 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuario_options_remove_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=2, max_length=100, verbose_name='Nome completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ocupacao',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário'), ('gerente', 'Gerente')], default='cliente', max_length=20, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Número de telefone inválido')], verbose_name='Telefone'),
        ),
    ]
