# Generated by Django 5.2.5 on 2025-09-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_options_usuario_email_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'ocupacao': 'funcionario'}, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to='app.usuario', verbose_name='Vendedor'),
        ),
        migrations.RemoveField(
            model_name='venda',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'ocupacao': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='app.usuario', verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
